site_name: Colonel By Computer Science
pages:
    - Home: index.md
    - Recursion: recursion.md
    - Dynamic Programming: dp.md
    - Graph Theory: graph.md
    - Ad Hoc: adhoc.md
    - STL Containers: stl.md
    - More Challenges: challenges.md
    - About: about.md
theme: material
theme_dir: theme
markdown_extensions:
  - codehilite
copyright: Colonel By Computer Science 2017